#!/bin/bash
# run it as sudo yes | sh ubuntu_software_installer.sh

# CURL
sudo apt-get install curl

# Brave
sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list
sudo apt update
sudo apt install brave-browser

# VS CODE 
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

# SKYPE (preview)
curl https://repo.skype.com/data/SKYPE-GPG-KEY | sudo apt-key add -
echo "deb [arch=amd64] https://repo.skype.com/deb unstable main" | sudo tee /etc/apt/sources.list.d/skype-unstable.list

# KODI
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:team-xbmc/ppa

## INSTALL
sudo apt-get update
sudo apt-get install kodi google-chrome-stable code terminator git skypeforlinux

#CLIPIT 
sudo apt-get install clipit

# NVM
curl https://raw.githubusercontent.com/creationix/nvm/v0.33.4/install.sh | bash

# NODE
nvm install stable

## GIT config
git config --global user.email "user@mail.com"
git config --global user.name "username"

# AVN
npm install -g avn avn-nvm avn-n
avn setup

echo Finished Installing Programs!
